[package]
name = "text_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "3.0.0"
memchr = "2.7.2"

[[bin]]
name = "my_vim"
path = "src/bin/main.rs"
